sudo: false

dist: xenial

language: ruby

rvm:
  - 2.5.1

cache:
  bundler: true
  - yarn

services:
  - postgresql

before_install:
  - nvm install --lts
  - gem install bundler
  - gem install rails -v 5.2.4.3

before_script:
  - bundle install
  - yarn
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

services:
  - redis-server

addons:
  postgresql: "10.12"

env:
  global:
    - CI=true
    - RAILS_ENV=test