version: '3.4'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/bicudafc-api
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: redis
    image: redis:6.0.8

  sidekiq:
    container_name: sidekiq
    build: .
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/bicudafc-api
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules: